import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-gray-50">
          <nav className="bg-blue-600 text-white shadow-md">
            <div className="container mx-auto px-4">
              <div className="flex justify-between items-center py-4">
                <Link href="/" className="text-xl font-bold">
                  Sistema de Estoque
                </Link>
                <div className="hidden md:flex space-x-6">
                  <Link href="/" className="hover:text-blue-200">
                    Dashboard
                  </Link>
                  <Link href="/produtos" className="hover:text-blue-200">
                    Produtos
                  </Link>
                  <Link href="/categorias" className="hover:text-blue-200">
                    Categorias
                  </Link>
                  <Link href="/movimentacoes" className="hover:text-blue-200">
                    Movimentações
                  </Link>
                  <Link href="/relatorios" className="hover:text-blue-200">
                    Relatórios
                  </Link>
                </div>
                <div className="md:hidden">
                  <button className="focus:outline-none">
                    <svg className="h-6 w-6 fill-current" viewBox="0 0 24 24">
                      <path d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"></path>
                    </svg>
                  </button>
                </div>
              </div>
            </div>
          </nav>

          <main className="container mx-auto px-4 py-8 text-gray-800">
            {children}
          </main>

          <footer className="bg-gray-100 border-t mt-auto">
            <div className="container mx-auto px-4 py-6">
              <p className="text-center text-gray-600">
                Sistema de Gerenciamento de Estoque © {new Date().getFullYear()}
              </p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}